name: seqcomp
channels:
  - conda-forge
dependencies:
  - python=3.11
  - ffmpeg
  - x264
  - x265
  - numpy
  - opencv
  - psutil
  - tqdm
  - pytest
  - pytest-cov
  - pip
  - pip:
      - build>=1
      - twine>=5
